### ISSUE TITLE
jquery is not loading i dont know i have tried in all ways but iam facing issue at $...velocity() is not a function

### ISSUE THREAD

**Issue by ishaqshaik222** [InfomediaLtd/angular2-materialize#325] opened 2017-07-19 13:21 UTC
altair_admin_common.min.js:2 Uncaught TypeError: $(...).velocity is not a function
    at Object.card_expand (altair_admin_common.min.js:2)
    at Object.init (altair_admin_common.min.js:2)
    at HTMLDocument.<anonymous> (altair_admin_common.min.js:2)
    at c (common.min.js:2)
    at Object.fireWith [as resolveWith] (common.min.js:2)
    at Function.ready (common.min.js:2)
    at HTMLDocument.s (common.min.js:1)

**Comment by rubyboy** [comment] 2017-07-22 06:59
Duplicate of https://github.com/InfomediaLtd/angular2-materialize/issues/326

**Closed by rubyboy** 2017-07-22 06:59 UTC
