### ISSUE TITLE
TypeError: e.velocity is not a function

### ISSUE THREAD

**Issue by lucacox** [InfomediaLtd/angular2-materialize#78] opened 2016-08-09 15:25 UTC
I'm trying to use angular2-materialize with `angular-cli@webpack`. 

I've managed to load the stub app without errors, but if I try to include a sideNav in the application, when I click on the menu button I get this exception:

```js
EXCEPTION: TypeError: e.velocity is not a function

TypeError: e.velocity is not a function
    at HTMLAnchorElement.<anonymous> (materialize.js:3)
    at HTMLAnchorElement.dispatch (jquery.js:4737)
    at HTMLAnchorElement.elemData.handle (jquery.js:4549)
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (ng_zone_impl.js:44)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at HTMLAnchorElement.ZoneTask.invoke (zone.js:423)
```

Is there a way to fix this?

---

My `main.ts` file is:

```ts
import { bootstrap } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';


// import angular2-materialize: once per project
import 'jquery';
import "materialize"
import "materialize-css"
import "angular2-materialize";

import { AppComponent, environment } from './app/';

if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent);
```

`app.component.ts` file:

```ts
import { Component } from '@angular/core';
import { MaterializeDirective } from 'angular2-materialize';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  directives: [ MaterializeDirective ]
})
export class AppComponent {

}
```

and `app.component.html` file

```html
<div class="container">
  <ul id="slide-out" class="side-nav">
    <li>
      <div class="userView">

      </div>
    </li>
    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
  </ul>
  <a materialize="sideNav" href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
</div>
```

**Comment by rubyboy** [comment] 2016-08-09 16:44
Duplicate of https://github.com/InfomediaLtd/angular2-materialize/issues/20 and https://github.com/InfomediaLtd/angular2-materialize/issues/48

**Closed by rubyboy** 2016-08-09 16:44 UTC

**Comment by lucacox** [comment] 2016-08-10 08:32
I think it's a little different because I am using `angular-cli@webpack` and not vanilla webpack. In angular-cli you do not have direct access to webpack configuration so I can not apply @camarrone workaround in #20. But I will check those issues to track updates

**Comment by MarkusPint** [comment] 2016-08-17 16:50
@camarrone workaround results in buggy behaviour with modals

**Comment by wceolin** [comment] 2016-09-11 17:27
@lucacox did you figure out how to solve this with `angular-cli@webpack`? I'm having the same issue.

**Comment by lucacox** [comment] 2016-09-12 07:26
@wceolin Unfortunately no...

**Comment by rubyboy** [comment] 2016-09-12 07:59
There are some [new instructions](https://github.com/InfomediaLtd/angular2-materialize#installing--configuring-angular2-materialize-in-projects-created-with-angular-cliwebpack-100-beta11-webpack8) added by @leonardobazico in his latest PR (https://github.com/InfomediaLtd/angular2-materialize/pull/105) fixing issues for the ```angular-cli@webpack```. Maybe try running through them using the latest version (5.1.1) that includes his fix.
If that doesn't work, maybe @leonardobazico can share his setup that works.

**Comment by wceolin** [comment] 2016-09-12 08:01
Thanks, @leonardobazico. I've just tried his instructions, and it's working now. :)

The missing part for me was adding `jQuery` to `angular-cli.json`.

**Comment by bernhardwaidacher** [comment] 2016-09-25 12:26
@wceolin I'm having the same issue and done everything as described in the instructions, however, this velocity thing is still not found. Could you maybe share your setup so I could compare mine with it? Thanks in advance

**Comment by wceolin** [comment] 2016-09-25 18:59
@bernhardwaidacher are you adding this to your `angular-cli.json` file?

```
"scripts": [
  "../node_modules/jquery/dist/jquery.js",
  "../node_modules/materialize-css/dist/js/materialize.js"
],
```

Please, also note that you need the version `2.2.4` as `jQuery 3` isn't compatible. You can have a look at my [working repository](https://github.com/zoonk/website).

**Comment by bernhardwaidacher** [comment] 2016-09-28 19:58
@wceolin thanks for sharing
I've compared our projects, only difference seems that I have
`"../node_modules/jquery/dist/jquery.min.js",`

and you have it without the min. But if I do that, i have the problem that whole application is not working because `jQuery.easing.swing'` is mssing

**Comment by gdlm91** [comment] 2016-10-26 02:15
@bernhardwaidacher did you manage to get it to work? I followed the instructions to install with angular-cli@webpack, but it doens't work. 

When I use jquery.min.js, the e.velocity problem appears. When I change it to jquery.js, then the 'swign of undefined' appears.

**Comment by n0mid** [comment] 2017-03-22 09:27
@gdlm91 for me helped:
window.$ = window.jQuery;
in app.component. 

I found what jQuery(selector).velocity works, but $(selector).velocity doesn't.

**Comment by joelmarty** [comment] 2017-04-13 11:11
@n0mid : I have the same issue (angular2-materialize with angular-cli@webpack) that $(selector).velocity is not defined but jQuery(selector).velocity is but I don't understand from your post where you would put that bit of code.

**Comment by n0mid** [comment] 2017-04-27 04:27
@joelmarty I have put in constructor of app.component.

**Comment by thespacious** [comment] 2017-04-29 20:55
So i tried that same thing that worked for @n0mid, I put window['$'] = window['jQuery'] in my app.component,  and @bernhardwaidacher's solution, but I still get the same error trying to create and expandable fab with this code (which I took form materialize docs):

`<nav>
    <div class="nav-wrapper transparent"> <a href="" class="brand-logo left">{{title}}</a>
        <div materialize class="fixed-action-btn horizontal click-to-toggle">
            <a class="btn-floating btn-large red right">
                <i class="material-icons">menu</i>
            </a>
            <ul>
                <li><a class="btn-floating red right"><i class="material-icons">insert_chart</i></a></li>
                <li><a class="btn-floating yellow darken-1 right"><i class="material-icons">format_quote</i></a></li>
                <li><a class="btn-floating green right"><i class="material-icons">publish</i></a></li>
                <li><a class="btn-floating blue right"><i class="material-icons">attach_file</i></a></li>
            </ul>
        </div>
    </div>
</nav>`

in angular-cli v1.0.0

Error, caused when I try to expand the FAB:

`Uncaught TypeError: d.find(...).velocity is not a function
    at c (materialize.js:4)
    at HTMLAnchorElement.<anonymous> (materialize.js:4)
    at HTMLDocument.dispatch (jquery.js:4737)
    at HTMLDocument.elemData.handle (jquery.js:4549)
    at Zone.runTask (zone.js:165)
    at HTMLDocument.ZoneTask.invoke (zone.js:460)`

Does anyone else have fix for this?
