### ISSUE TITLE
Can't build a collapsible list of components

### ISSUE THREAD

**Issue by Fistynuts** [InfomediaLtd/angular2-materialize#217] opened 2017-01-26 09:54 UTC
I'm having a problem with collapsible lists where each list item uses a component. I have a modal dialog component which contains a list:

```html
<ul *ngIf="linkableSystems" materialize="collapsible" class="collapsible" data-collapsible="accordion">
    <li *ngFor="let system of linkableSystems">
        <userLinkedAccountManagementComponent [systemName]="system"></userLinkedAccountManagementComponent>
    </li>
    <li>
        <div class="collapsible-header">Extra test</div>
        <div class="collapsible-body">Body</div>
    </li>
</ul>
```

I want each list item to be an instance of `userLinkedAccountManagementComponent`, which contains the relevant `<div>` elements:

```html
<div class="collapsible-header">
    Component header
</div>
<div class="collapsible-body">
    Component body
</div>
```

What happens is that the header elements for all items are shown as expected. Clicking the items that use the component does nothing - they don't expand. Clicking the "Extra test" item, which doesn't use a component, expands as expected.

I'm obviously missing something but can't work out what. Any help would be appreciated!

**Comment by Slaskefar** [comment] 2017-04-05 06:42
I've been having the same issue as you, though I think I've been able to find the cause of the issue. I've been able to recreate the bug, where the collapsible item does nothing on click with this code:

`<ul class="collapsible" data-collapsible="accordion" *ngFor="let collection of _quizCollections">
          <li *ngFor="let question of _questions | async">
            <div class="collapsible-header">{{question.name}}</div>
            <div class="collapsible-body"><span>body text</span></div>
          </li>
        </ul>`

When I remove the *ngFor from the <ul> tag, the collapsible works again - like this:

`<ul class="collapsible" data-collapsible="accordion">
          <li *ngFor="let question of _questions | async">
            <div class="collapsible-header">{{question.name}}</div>
            <div class="collapsible-body"><span>body text</span></div>
          </li>
        </ul>`

**Comment by evanhdc** [comment] 2017-07-04 06:57
Just saw exactly the same issue. @Slaskefar this is caused by using component instance as a list item, rather than having a *ngFor in ul tag.

As @Fistynuts stated, it works fine when the list item is not a component. I updated angular2-materialize to the latest version but am still seeing this problem. @rubyboy do you have any idea on what we've been missing? Thanks in advance!

**Comment by philschanely** [comment] 2017-07-06 13:11
@Fistynuts I ran into this as well. I believe that Materialize's JS setup expects`.collapsible` elements to have the `<li>` elements as direct children and then the `.collapsible-header` and `.collapsible-body` as direct children of the `<li>`. Therefore, Angular's tag-based component—`<userLinkedAccountManagementComponent>` in your case—breaks the functionality since `.collapsible-header` and `.collapsible-body` are created a layer deeper. Solve this by changing the   `userLinkedAccountManagementComponent` selector to allow either a tag or attribute application like this:

```js
@Component({
  // ...
  selector: "userLinkedAccountManagementComponent,[userLinkedAccountManagementComponent]",
  // ...
})
```
and then use the attribute selector directly on the `<li>` elements in your template code like this:

```html
<ul *ngIf="linkableSystems" materialize="collapsible" class="collapsible" data-collapsible="accordion">
    <li *ngFor="let system of linkableSystems" 
       [userLinkedAccountManagementComponent] [systemName]="system"></li>
    ...
</ul>
```
Hope this helps!

**Comment by rubyboy** [comment] 2017-09-02 07:02
@Fistynuts @evanhdc , is this issue still a problem? A plunker/repo that reproduces the problem would be great to help solve it. Thanks.

**Comment by evanhdc** [comment] 2017-09-02 16:06
Phil's solution worked like a charm. You may close this ticket. Thanks!

**Closed** 2017-09-03 05:25 UTC
