### ISSUE TITLE
MaterializeDirective is part of declarations of 2 modules (AoT)

### ISSUE THREAD

**Issue by Shiroh1ge** [InfomediaLtd/angular2-materialize#210] opened 2017-01-13 22:07 UTC
I know this has been answered before, but my problem is a little different and I don't know what to do. I tried creating a SharedModule and declaring the directive there, and I have not imported it anywhere else. The error comes from node_modules for some reason. 
`Type MaterializeDirective in node_modules/angular2-materialize/dist/materialize-directive.d.ts is part of the declarations of 2 modules: MaterializeModule in node_modules/angular2-materialize/dis
t/materialize-module.d.ts and  SharedModule `
And this is my SharedModule: 

```
import {NgModule}            from '@angular/core';
import {CommonModule}        from '@angular/common';
import {FormsModule, ReactiveFormsModule}         from '@angular/forms';
import {MaterializeDirective} from "angular2-materialize";

@NgModule({
  imports: [CommonModule, ],
  declarations: [MaterializeDirective],
  exports: [CommonModule, FormsModule, ReactiveFormsModule, MaterializeDirective]
})
export class SharedModule {
}
```

`
I have no idea why it's checking in node_modules. I'm using Angular 2.4.1 and the Webpack starter pack with AoT enabled. When I run the app in JiT it works fine though. Any help is appreciated!

**Comment by jomarbarnobal** [comment] 2017-01-17 17:55
Separate you materializedirective
Heres what i did

create a module a materialize.module.ts in your root directory
im using cli so i put my module here /src/app/materialize.module.ts

//materialize.module.ts
import { NgModule } from '@angular/core';
import { MaterializeDirective } from 'angular2-materialize';

@NgModule({
 declarations: [ MaterializeDirective]
})

export class YourMaterializeDirective {}

then import it thi in you root module.ts

**Comment by Dillinjer** [comment] 2017-01-22 15:26
I'm encountering the same problem. Any ideas in how to fix it?

**Comment by Dillinjer** [comment] 2017-01-22 23:50
@rubyboy Any idea in how to fix this issue? The problem happens when splitting the app in multiple modules with lazy loading then compile with AoT. I tried with Angular 2.4.4 and angular2-materialize 6.6.0 and got the same result as Shiroh1ge. 
This is the only issue missing for I to build my app for production.

**Comment by jomarbarnobal** [comment] 2017-01-23 07:21
@Dillinjer  are you using angular CLI ?

**Comment by Dillinjer** [comment] 2017-01-23 10:31
@jomarbarnobal I'm using just ngc with webpack using the following commands:
ngc -p tsconfig.aot.json && webpack --config webpack.config.prod.js --progress --profile --bail

tsconfig.aot.json:
`{
  "compilerOptions": {
    "module": "es2015",
    "target": "es5",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "outDir": "./public/js/app"
  },
  "exclude": [
    "node_modules",
    "public/js",
    "client/app/polyfills.ts"
  ],
  "angularCompilerOptions": {
    "skipMetadataEmit": true
  }
}`

webpack.config.common.js:
`const webpack = require('webpack');

module.exports = {
  entry: {
    'app': './client/app/main.ts'
  },

  resolve: {
    extensions: ['.js', '.ts']
  },

  module: {
    loaders: [
      {
        test: /\.ts$/,
        use: [
            'awesome-typescript-loader',
            'angular2-template-loader',
            'angular2-router-loader'
        ]
      },
      {
        test: /\.html$/,
        use: 'html-loader'
      },
      {
        test: /\.css$/,
        use: 'raw-loader'
      },
      {
        test: /.(png|woff(2)?|eot|ttf|svg)(\?[a-z0-9=\.]+)?$/,
        use: 'url-loader?limit=100000'
      }
    ]
  },

  plugins: [
    new webpack.ContextReplacementPlugin(
        // The (\\|\/) piece accounts for path separators in *nix and Windows
        /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
        './client/app' // location of your src
    ),
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery",
      Hammer: "hammerjs/hammer"
    })
  ]
};`

webpack.config.prod.js
`var webpack = require('webpack');
var webpackMerge = require('webpack-merge');
var commonConfig = require('./webpack.config.common.js');

module.exports = webpackMerge.smart(commonConfig, {
    entry: {
        'app': './client/app/main.aot.ts'
    },

    output: {
        path: './public/js/app',
        filename: 'bundle.js',
        publicPath: '/js/app/',
        chunkFilename: '[id].[hash].chunk.js'
    },

    module: {
        loaders: [
            {
                test: /\.ts$/,
                use: [
                    'awesome-typescript-loader',
                    'angular2-template-loader',
                    'angular2-router-loader?aot=true&genDir=public/js/app'
                ]
            }
        ]
    },

    plugins: [
        new webpack.NoErrorsPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: false
        })
    ]
});`

**Comment by cloette** [comment] 2017-01-30 20:59
Having this issue as well.

**Comment by Maistho** [comment] 2017-01-31 00:53
Don't declare it yourself, just put it in the imports of your appcomponent.

```
// app.component.ts
...

import { MaterializeModule } from 'angular2-materialize';

...

imports: [
    MaterializeModule,
],

...
```

**Comment by Hyperparticle** [comment] 2017-02-04 19:27
I imported `MaterializeModule` instead of `MaterializeDirective` in `app.module.ts`, and it worked for me.

```
import {MaterializeModule} from "angular2-materialize";

@NgModule({
  imports: [
    //...
    MaterializeModule
  ],
  //...
})
```

**Comment by rubyboy** [comment] 2017-02-05 06:09
@Shiroh1ge @Dillinjer @cloette are you able to confirm if switching to importing the MaterializeModule and adding it to the app's module imports solved the issue for you? Thanks

**Comment by Dillinjer** [comment] 2017-02-05 18:16
I can't confirm 100% that fixed because I'm having other troubles with AOT but that workaround seems to make my app build without that error

**Comment by Dillinjer** [comment] 2017-02-06 00:57
@rubyboy I got my AOT to compile properly and I can confirm that it works. The only thing weird that has nothing to do with materialize is that AOT didn't make my .js bundles any smaller, but it should have been smaller because it should remove the compiler.

**Comment by rubyboy** [comment] 2017-02-06 06:05
@Dillinjer thanks for confirming that. I'll close this issue now.

**Closed by rubyboy** 2017-02-06 06:05 UTC

**Comment by Shiroh1ge** [comment] 2017-02-06 16:15
Sorry for not responding, for some reason I was not getting any notifications and just saw the notification that the issue was closed. Anyway, yes, I have fixed the problem by just importing the module, I guess I had  a lack of understanding of how the declarations/imports should be used. Sorry for the inconvenience!

**Comment by Hyperparticle** [comment] 2017-02-06 18:45
@rubyboy The `README` says to use `MaterializeDirective`, but it breaks AOT as-is. Should this be documented somewhere?

**Comment by rubyboy** [comment] 2017-02-12 08:00
@Hyperparticle thanks so much for pointing this out. I've fixed the README to refer to the MaterializeModule.
