### ISSUE TITLE
Functions not found with latest version of AngularClass-webpack-starter

### ISSUE THREAD

**Issue by denneulin** [InfomediaLtd/angular2-materialize#48] opened 2016-06-17 09:11 UTC
I have an error when I try to use angular2-materialize with new version of angularClass boilerplate.
I can add a simple material design button but if I add a tooltip, the JS function is not found.

![screen shot 2016-06-17 at 11 08 04](https://cloud.githubusercontent.com/assets/1647464/16145953/d6dd2660-347b-11e6-9bfb-449bf3429cf5.png)

**Comment by snarum** [comment] 2016-06-17 10:15
I'm not using the AngularClass, but I have similar problems after implementing webPack. First I got the same error as on issue https://github.com/InfomediaLtd/angular2-materialize/issues/5. After resolving that I get 
    Couldn't find materialize function ''dropdown' on element or the global Materialize object
I'm very new to webPack, so I might have done something silly :)

**Comment by denneulin** [comment] 2016-06-20 15:32
maybe @rubyboy can help us ;)

**Comment by rubyboy** [comment] 2016-06-20 17:12
@denneulin @snarum I'll try to take a look tomorrow.

Are you using this starter? https://github.com/AngularClass/angular2-webpack-starter

If you do, have you tried the fork with Materialize? https://github.com/InfomediaLtd/angular2-webpack-starter
It hasn't been updated for a while, so maybe it's related to some recent changes. I can check that out later this week.

**Comment by denneulin** [comment] 2016-06-21 07:18
Yes, I am using the AngularClass repo.

I make angular2-materialize works with a previous version of AngularCass starter but not with a recent one.

**Comment by snarum** [comment] 2016-06-21 07:30
I've spent two whole days on webPack now, and still cant get around this problem. Here is the things that I experience:

Using the angular2-webpack-starter works 100%. 
Using the webpack.config.js from Starter (with minimal adaptations) on my solution i can't compile:
    ERROR in C:\work\PB Dashboard\dev\Cockpit\typings\browser\ambient\node\index.d.ts
    (514,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.

When applying the fix suggested in #5 on my own webpack.config.js I get 
    Error: Couldn't find materialize function ''leanModal' on element or the global Materialize object.
whenever I load a page with modals.

I'm starting to run out of time, so if I cant make this work today I think I'll have to try to bundle with jspm instead.

Any hints or suggestions is greatly appreciated..

**Comment by rubyboy** [comment] 2016-06-21 13:44
I use JSPM in all my projects. Personally, I prefer it and the additional of private git repositories and Github support is awesome (+ all the other features it has, including in-browser transpilation).

I tried forking the latest version and updating it with MaterializeCSS: https://github.com/rubyboy/angular2-webpack-starter
I get the same problems as https://github.com/InfomediaLtd/angular2-materialize/issues/20 , which we haven't resolved yet. There is something funky going on with the velocity library. Not really sure how to solve it. As if it's not being loaded in the correct order or being brought with a shim that is not the real library.

**Comment by snarum** [comment] 2016-06-22 06:46
To me it's good news that you have managed to reproduce. Great if you keep us updated if there is any development.

**Comment by TheClark** [comment] 2016-06-24 18:47
Same here, very glad you recreated it, I was going crazy.  Any progress on it by chance?  If by some miracle I figure it out, will post back...

**Comment by rubyboy** [comment] 2016-06-25 03:12
Just to comment that this is not happening with jspm, which are are using in production.
It's a specific problem that is caused by the way Webpack is configured. Probably some loading order or missing dependencies. I'm pretty lost there, as I'm not a Webpack expert.

**Comment by TheClark** [comment] 2016-06-27 15:30
Me neither, just fumbling around with webpack!  Started fresh this morning, new error:

Error: Cannot resolve module 'materialize'

Googling around to see what I may have messed up this time....

**Comment by TheClark** [comment] 2016-06-27 15:36
Duh... npm install --save materialize

Back to the original issue stated by @denneulin

I really want to use this project, going to keep digging....

**Comment by rubyboy** [comment] 2016-07-10 10:40
I've got some breakthrough. The problem is that MaterializeCSS expects jQuery to be defined on the window. If you add the following line at the top of materialize.js then everything works fine: ```window.jQuery = $```

I think this is something that should be fixed in MaterializeCSS, but there must be a configurable way in Webpack to add this line to the top of the imported script when it's loaded, right? Looking for it now...

**Comment by rubyboy** [comment] 2016-07-10 12:41
Got it! (I think 😀 )

Add the following bit ``` "window.jQuery": "jquery",``` to the ```webpack.ProvidePlugin```, like this:
```js
    new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
        "window.jQuery": "jquery",
        Hammer: "hammerjs/hammer"
    }),
```

@denneulin @snarum @TheClark are you able to confirm if this solves the problem for you?
Thanks.

**Comment by rubyboy** [comment] 2016-07-10 12:53
Also, MaterializeCSS doesn't support jQuery 3.0.0, so make sure you ```npm install jquery@^2.2.4```

**Comment by rubyboy** [comment] 2016-07-11 15:17
Actually, I can see more issues. It's quite a rabbit hole...
Just to put more info here on the problem, I can see 3 different instances of jquery being created. Materialize adds its own functions to jquery (like tooltip, etc.) and because there are 3 instances of jquery it only handles one. when the angular wrapper tries calling "tooltip" it uses another.
So it's down to the Webpack configuration. Trying to figure out how to configure webpack to load jquery only once and provide it as a global for Materialize. Unfortunately I'm not a Webpack expert. Help would be highly appreciated...
If only everyone used jspm... 😀

**Comment by camarrone** [comment] 2016-07-29 13:37
Guys,

I don't know if this is the best solution but got it solved here:

1 - import the jquery.min.js in index.html 
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
`
2 - on webpack.conf.js add these lines:

```
  externals: {
    jquery: 'jQuery'
  },
```
Hope this solve the issue for you all using webpack.

Cheers!

**Comment by rubyboy** [comment] 2016-08-24 11:32
Try the latest version of angular2-materialize, compatible with RC5 and also separated from materialize-css (this is a breaking change - you will need to import materialize-css).
Here's a working example: https://github.com/InfomediaLtd/angular2-webpack-starter

**Closed by rubyboy** 2016-08-24 11:32 UTC

**Comment by AAAnderson7301** [comment] 2016-09-08 20:54
Please ignore my last comment, the issue is coming from UglifyJsPlugin. Removing this from my Prod build resolves the issue.

**Comment by criticalbh** [comment] 2016-10-10 11:19
in angular2-materialize documentation order is confusing. try instead of:
import { MaterializeModule } from 'angular2-materialize';
import "materialize-css";

do this: 

import "materialize-css";
import { MaterializeModule } from 'angular2-materialize';

**Comment by NatsuOnFire** [comment] 2016-11-16 16:52
@AAAnderson7301 
I prefer to change the mandle property instead of removing the plugin:
```
mangle: {
          screw_ie8: true,
          **keep_fnames: false**
},
```

But, is there a solution to keep the Uglify on the function names?

**Comment by marcellopato** [comment] 2016-11-17 23:19
Guys, it is too old, Angular2 Final is released so yours solutions are obsolete. Does not exist webpack anymore... it is installed inside angular-cli, right?
So, i´ve created my project using angular-cli, then npm angular2materialize and so on... still getting the same error... 

 @rubyboy 

`Uncaught Error: Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.`

**Comment by xtian7** [comment] 2016-12-29 20:23
Hello i have the same issue  i think on a sidebar, but i'm using meteor 
any idea please? 

modules.js?hash=2173015…:23992 Uncaught TypeError: d.velocity is not a function
    at HTMLAnchorElement.<anonymous> (modules.js?hash=2173015…:23992)
    at HTMLAnchorElement.dispatch (modules.js?hash=2173015…:29889)
    at HTMLAnchorElement.elemData.handle (modules.js?hash=2173015…:29701)
    at ZoneDelegate.invokeTask (modules.js?hash=2173015…:22445)
    at Zone.runTask (modules.js?hash=2173015…:22334)
    at HTMLAnchorElement.ZoneTask.invoke (modules.js?hash=2173015…:22515)

**Comment by Frawel** [comment] 2017-02-11 22:40
Hello,
Same Error Here:

Error: Couldn't find materialize function ''tooltip' on element or the global Materialize object.↵    at ZoneAwareError (http://localhost:8080/js/polyfills.bundle.js:15656:33)

**Comment by j-borg** [comment] 2017-03-21 15:13
@DarkChopper I had the same issue with Meteor (and no webpack). Using the Meteor package instead of the npm package fixes the problem - https://atmospherejs.com/materialize/materialize

Remove the import of materialize-css from your main file.

**Comment by KrunalC28** [comment] 2018-07-08 11:01
I am getting same error, is there any update with new angular starter project ?
