### ISSUE TITLE
Datepicker throws error in IE11

### ISSUE THREAD

**Issue by pchristou** [InfomediaLtd/angular2-materialize#60] opened 2016-07-08 09:09 UTC
Hi,

This may be linked to issue #58 but IE11 throws up an error upon the user selecting a date (or clicking any other buttons in the date widget). The error seems somewhat generic so is difficult to track down to a specific line... Note that the functionality still works but the same error is not thrown in Firefox or Chrome. 

The markup I'm using is simply `<input type="date"  materialize="pickadate" class="datepicker">`

Error that's thrown on selection / clear (highlighted line in image changes depending on whether the key pressed was a selection or clear command)

![ie11_error](https://cloud.githubusercontent.com/assets/18244820/16682730/db033fda-44f3-11e6-8025-d09299cb00e9.PNG)

**Comment by rubyboy** [comment] 2016-07-10 06:55
@pchristou Are you able to try it out with a simple MaterializeCSS import (no angular or wrapper) ? Just to confirm the problem is in the wrapper and not in MaterializeCSS itself.

Here's how you'd import the vanilla MaterializeCSS:
```html
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
```

**Comment by pchristou** [comment] 2016-07-11 10:19
@rubyboy vanilla materialize works. You can see there's no errors upon selecting a date.


![datepicker](https://cloud.githubusercontent.com/assets/18244820/16727465/19587630-4759-11e6-9bb8-90e6390d5bb8.png)

**Comment by rubyboy** [comment] 2016-07-11 14:02
I found the problem. Working on it (something to do with dispatching events in IE - it doesn't like the ```new Event("input")``` syntax).

**Comment by pchristou** [comment] 2016-07-11 14:11
@rubyboy Aha, sounds like this? http://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work

**Comment by rubyboy** [comment] 2016-07-11 14:37
Yeah, working this Polyfill into a TypeScript style: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by rubyboy** [comment] 2016-07-11 14:49
A fix has been released. I've tested and also released a new version to http://angular2-materialize.surge.sh and it seems to work fine on IE11 now.
@pchristou Are you able to verify and close the issue if it works? Thanks.

**Comment by pchristou** [comment] 2016-07-11 15:40
@rubyboy demo seems fine now. 

I included the 1 additional file and modified the materialize-directive.ts file in my own project then rebuilt and run the solution but it's still erroring. Anything else I need to do that I may be missing?

Thanks for the quick turnaround on this.

**Closed** 2016-07-12 15:03 UTC

**Comment by rubyboy** [comment] 2016-07-12 15:47
Sorry for not answering. Going on holidays :)
Hopefully you got it working...
Cheers.

**Comment by pchristou** [comment] 2016-07-12 16:04
Yep, all working. Have a good holiday!

**Comment by Chipintoza** [comment] 2016-08-24 15:15
Hello...
when i compiling typescript generate error:
src/materialize-directive.ts(118,69): error TS2350: Only a void function can be called with the 'new' keyword.

jQueryElement.on("change", e => nativeElement.dispatchEvent(new CustomEvent("input")));

**Comment by rubyboy** [comment] 2016-08-24 15:42
Me too. I ignore it in my project.
Any ideas how to fix it? It's the CustomEvent polyfill to be able to dispatch  a "change" event in all browsers.

**Comment by Chipintoza** [comment] 2016-08-24 21:37
I can not run your app. for testing

there is tsc errors:

[01:35:47] Starting 'tsc'...
/Users/Chipintoza/GSS Projects/materialize/angular2-materialize/app/app.module.ts(3,29): error TS2307: Cannot find module '@angular/forms'.
app/main.ts(1,8): error TS2656: Exported external package typings file '/Users/Chipintoza/GSS Projects/materialize/angular2-materialize/node_modules/zone.js/dist/zone.js.d.ts' is not a module. Please contact the package author to update the package definition.
src/materialize-directive.ts(118,69): error TS2350: Only a void function can be called with the 'new' keyword.
/Users/Chipintoza/GSS Projects/materialize/angular2-materialize/app/app.routing.ts(60,14): error TS4023: Exported variable 'routing' has or is using name 'ModuleWithProviders' from external module "/Users/Chipintoza/GSS Projects/materialize/angular2-materialize/node_modules/@angular/core/src/metadata/ng_module" but cannot be named.

**Comment by Chipintoza** [comment] 2016-08-25 10:14
you can change custom-event-polyfill.ts by:

function CustomEvent(type, bubbles, cancelable, detail) {
    var event = document.createEvent('CustomEvent');
    event.initCustomEvent(type, bubbles, cancelable, detail);
    return event;
}
if ("Event" in window) {
    CustomEvent.prototype = window.Event.prototype;
}
function createCustomEvent(type, params) {
    if (params === void 0) { params = { bubbles: false, cancelable: false, detail: undefined }; }
    var customEvent = Object.create(CustomEvent.prototype);
    return CustomEvent.call(customEvent, type, params.bubbles, params.cancelable, params.detail);
}
exports.createCustomEvent = createCustomEvent;

and use exported - createCustomEvent

**Comment by Chipintoza** [comment] 2016-08-25 10:15
you can change custom-event-polyfill.ts:

function CustomEvent(type, bubbles, cancelable, detail) {
    var event = document.createEvent('CustomEvent');
    event.initCustomEvent(type, bubbles, cancelable, detail);
    return event;
}
if ("Event" in window) {
    CustomEvent.prototype = window.Event.prototype;
}
function createCustomEvent(type, params) {
    if (params === void 0) { params = { bubbles: false, cancelable: false, detail: undefined }; }
    var customEvent = Object.create(CustomEvent.prototype);
    return CustomEvent.call(customEvent, type, params.bubbles, params.cancelable, params.detail);
}
exports.createCustomEvent = createCustomEvent;

and use exported createCustomEvent

**Comment by Chipintoza** [comment] 2016-08-25 10:50
i change it by:

`function CustomEvent(type: string, eventInitDict?: CustomEventInit) {
    var event = document.createEvent('CustomEvent');
    event.initCustomEvent(type, eventInitDict.bubbles, eventInitDict.cancelable, eventInitDict.detail);
    return event;
}

if ("Event" in window) {
    CustomEvent.prototype = (window as any).Event.prototype;
}

export function createCustomEvent(type: string, eventInitDict: CustomEventInit = { bubbles: false, cancelable: false, detail: undefined }): CustomEvent {
    let customEvent = Object.create(CustomEvent.prototype);
    return CustomEvent.call(customEvent, type, eventInitDict)
}
`
