### ISSUE TITLE
Parallax

### ISSUE THREAD

**Issue by moumoune** [InfomediaLtd/angular2-materialize#38] opened 2016-05-26 12:44 UTC
Hi,
I try to use parallax feature.

`
<div class="parallax-container" >
     <div class="parallax" materialize="parallax"><img src="app/maps/Plan_C5_R0_v1.png"></div>
</div>
`

This not work. How it's work, i havn't found nothing in the docs about that.

**Comment by moumoune** [comment] 2016-05-26 12:45
```
<div class="parallax-container" >
                    <div class="parallax" materialize="parallax"><img src="app/maps/Plan_C5_R0_v1.png"></div>
                </div>
```

**Comment by rubyboy** [comment] 2016-05-26 12:55
I've never actually used this feature of MaterializeCSS. But the way you've set it up looks fine. It should call the parallax function on that element. Maybe also try adding a "materialize" directive on its own, in addition?

Could you confirm if this is a MaterializeCSS issue or a problem with the directive? Here's a small boilerplate that may help:

```html
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  </head>
  <body>
  </body>
</html>
```

**Comment by moumoune** [comment] 2016-05-26 13:22
No problem with MaterializeCSS, so it's a directive problem I think.

**Comment by rubyboy** [comment] 2016-05-26 14:05
I just tried it and it seems to work well for me.
Here's the HTML I used for testing it:
```html
<div class="parallax-container">
      <div class="parallax" materialize="parallax"><img src="http://materializecss.com/images/parallax1.jpg"></div>
    </div>
    <div class="section white">
      <div class="row container">
        <h2 class="header">Parallax</h2>
        <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
      </div>
    </div>
    <div class="parallax-container">
      <div class="parallax" materialize="parallax"><img src="http://materializecss.com/images/parallax2.jpg"></div>
    </div>
```

**Comment by rubyboy** [comment] 2016-05-29 02:54
@moumoune have you had a chance to give this a try?

**Comment by rubyboy** [comment] 2016-06-13 16:34
No further activity. Closing...

**Closed by rubyboy** 2016-06-13 16:34 UTC

**Comment by hugocalheira** [comment] 2017-05-10 19:50
How can I customize the parallax scrolling speed?

**Comment by rubyboy** [comment] 2017-05-11 04:55
@hugocalheira you can pass any params to the MaterializeCSS using the ```materializeParams``` attribute. So, if you figure out how MaterializeCSS lets you customize speed then you can set that in the template (or do that via ```materializeAction``` programmatically).
As for how to customize speed or any other behavior I suggest checking the MaterializeCSS repo or code itself. I haven't seen anything on its documentation, so maybe it's not supported. You can open an issue in the original repo: https://github.com/Dogfalo/materialize/issues

**Comment by sivadinesh1** [comment] 2017-08-06 06:17
The root cause of the problem mentioned here is with angular. In my case when I wrap the  materializecss code with <div *ngfor > materializecss parallax code </div> this will not render the images alone. if i remove *ngfor and copy paste the iteration everything works fine.
so basically when there is a wrapper over the materializecss parallax code this breaks. because the parallax has to be directly attached to the body tag, but when we wrap it with div this does not work. 
But not sure of the soultion. It would be great if someone post the solutions.

**Comment by gan-mel** [comment] 2018-09-20 09:45
> The root cause of the problem mentioned here is with angular. In my case when I wrap the materializecss code with <div *ngfor > materializecss parallax code this will not render the images alone. if i remove *ngfor and copy paste the iteration everything works fine.
> so basically when there is a wrapper over the materializecss parallax code this breaks. because the parallax has to be directly attached to the body tag, but when we wrap it with div this does not work.
> But not sure of the soultion. It would be great if someone post the solutions.

Have you found a way to resolve this? doesn't work with Angular 6 for me


>>> Update - if anyone is looking at this, this is indeed an issue with angular with Materialize, and this library makes it work together: https://www.npmjs.com/package/ngx-materialize
