### ISSUE TITLE
e.velocity is not function urgency please

### ISSUE THREAD

**Issue by chandumunna** [InfomediaLtd/angular2-materialize#89] opened 2016-08-21 04:30 UTC
html page -->

`<img class="materialboxed" width="650" src="src file">`

ts page-->
import { Component, OnInit, AfterViewInit } from '@angular/core';
declare var $:any;
declare var Materialize:any;
import {MaterializeDirective} from "angular2-materialize";
@Component({
  selector: 'app-home',
  directives:[MaterializeDirective],
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})
export class HomeComponent implements AfterViewInit {

  constructor() { }
  ngAfterViewInit(){
    $('.materialboxed').materialbox();
  }

}

**Comment by rubyboy** [comment] 2016-08-21 05:22
Duplicate of https://github.com/InfomediaLtd/angular2-materialize/issues/88

**Closed by rubyboy** 2016-08-21 05:22 UTC
