### ISSUE TITLE
Couldn't find materialize function...

### ISSUE THREAD

**Issue by CNSKnight** [InfomediaLtd/angular2-materialize#155] opened 2016-11-03 17:58 UTC
While working to roll up recent modal refactors into some code, adding the (seemingly extraneous) ``class="modal-trigger" [materializeActions]="modalActions"  (click)="openModal()"`` The titled error is thrown. Debugging I found this odity:
![image](https://cloud.githubusercontent.com/assets/220025/19978373/1d22d610-a1cd-11e6-9229-0f431b0f61eb.png)

The emitted event call looks like this:
```
  openModal() {
    this.modalActions.emit({action:"modal", params:['open']});
  }
```

> Aside: I see in the repo export MaterializeActions that have not made into angular2-materialize@5.2.1?

**Comment by ihabZhaika** [comment] 2016-11-03 18:28
i copied the example code in npm , gives the same error
`Uncaught Error: Couldn't find materialize function ''leanModal' on element or the global Materialize object.
    at HTMLDocument.<anonymous> `

**Comment by ihabZhaika** [comment] 2016-11-03 19:03
same error when try the select example  on the githup page
`app.bundle.js:30428 Uncaught Error: Couldn't find materialize function ''material_select' on element or the global Materialize object.`

**Comment by rubyboy** [comment] 2016-11-04 06:17
@ihabZhaika does the code in the repository work for you? Do other MaterializeCSS functions work? I think it may be related to wrong import of Materialize (it can't find it or it's got the wrong one)

**Comment by rubyboy** [comment] 2016-11-04 06:18
@CNSKnight same question. If you share your repository it may be easier for people to try and help out.

**Comment by CNSKnight** [comment] 2016-11-04 11:47
@ihabZhaika - what does that mean "does the code in the repo...".
eg my sideNav works fine. is when called via the .emit, the problem occurs. Via the screenshot I think you can see that "modal" is not being parsed out as the functionName passed in, though the construct looks correct. This may not be a n2-mat. issue at all but I've not tested other directives w/eventEmitter calls.

**Comment by ihabZhaika** [comment] 2016-11-04 13:49
@rubyboy 
i tried the model example in the guide , i have the directive imported , the input field example works ,
but i get the following error
`
materialize-directive.js:197 Uncaught Error: Couldn't find materialize function ''modal' on element or the global Materialize object`

and where i can find the components and their demo code  , and do i have to do any special thing for the components in http://materializecss.com/ , such open close etc so they can work in the html page ?

**Comment by rubyboy** [comment] 2016-11-05 04:26
@CNSKnight I was referring to the example of opening a modal in the repo: https://github.com/InfomediaLtd/angular2-materialize/blob/master/app/components/dialogs.ts
When you clone the repo and run it, does it work for you?
If you provide a repository that reproduces the problem is may be easier for others to help you. The more details the better.

@ihabZhaika maybe you haven't imported MaterializeCSS JS? This error usually means that MaterializeCSS hasn't been imported properly before angular2-materialize or that it's the wrong version (older version that doesn't have the "modal" function.

**Comment by ihabZhaika** [comment] 2016-11-05 16:08
@rubyboy 
i think i have every thing as it should,
this the project link if you can take a look , npm install , npm run serve
https://drive.google.com/open?id=0B_AFMME1kY1ocGduSlNvWFI3RGs

the code are in app.component.ts , app.component.html

**Comment by rubyboy** [comment] 2016-11-06 06:10
@ihabZhaika I tried reproducing on your repo but everything worked well for me. Not sure what is the difference between us two (I'm using a Mac)...

Here's what I did:
First, I had to install a few things because your project was missing them:
```js
npm install --save-dev copy-webpack-plugin
npm install --save angular2-materialize
```
Then, I added the following bit to the end of app.component.html:
```html
<hr/>
<hr/>
<select materialize="material_select" [materializeSelectOptions]="selectOptions">
    <option value="" disabled selected>Choose your option</option>
    <option *ngFor="let option of selectOptions" [value]="option.value">{{option.name}}</option>
</select>
<hr/>
<hr/>
```
And the corresponding JS to app.component.ts:
```js
private selectOptions = [
        {value:1,name:"Option 1"},
        {value:2,name:"Option 2"},
        {value:3,name:"Option 3"}
    ];
```

Here's how it looks:
![image](https://cloud.githubusercontent.com/assets/1908166/20035726/6200a9ec-a3f8-11e6-8210-465834c0389e.png)

**Comment by rubyboy** [comment] 2016-11-06 06:12
@CNSKnight I'm pretty sure your issue is with the "modal" keyword. You need to install the latest MaterializeCSS. This new function was introduced only in the latest version (previously is was called "leanModal"). The MaterializeCSS code with this new function is here: https://github.com/Dogfalo/materialize/blob/master/js/modal.js#L174

**Comment by ihabZhaika** [comment] 2016-11-06 06:44
@rubyboy
those two are installed but i forgot to do --save when i did them,
 i will retry to setup other project , if didnt work ,as this weird

**Comment by rubyboy** [comment] 2016-12-26 07:26
Closing...

**Closed by rubyboy** 2016-12-26 07:26 UTC

**Comment by Smitjohn** [comment] 2017-04-05 12:28
I am facing same issue like - 

![image](https://cloud.githubusercontent.com/assets/26926265/24705404/620625a0-1a29-11e7-8ab9-661dc85da379.png)


webpack.config.js :

**Comment by faisal-web** [comment] 2017-07-05 11:18
GET http://localhost:4200/node_modules/materialize-css/dist/css/materialize.css 
localhost/:13 GET http://localhost:4200/node_modules/jquery/dist/jquery.js 
localhost/:14 GET http://localhost:4200/node_modules/hammerjs/hammer.js 
localhost/:15 GET http://localhost:4200/node_modules/materialize-css/dist/js/materialize.js 
index.js:4 Uncaught Error: Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.
    at Object.../../../../angular2-materialize/dist/index.js (index.js:4)
    at __webpack_require__ (bootstrap 5ee703a…:54)
    at Object.../../../../../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap 5ee703a…:54)
    at Object.../../../../../src/main.ts (environment.ts:8)
    at __webpack_require__ (bootstrap 5ee703a…:54)
    at Object.2 (main.ts:11)
    at __webpack_require__ (bootstrap 5ee703a…:54)
    at webpackJsonpCallback (bootstrap 5ee703a…:25)
    at main.bundle.js:1

**Comment by faisal-web** [comment] 2017-07-05 11:19
materialize.css,  jquery.js, hammer.js, materialize.js in not work
